# Generated by Django 3.0.6 on 2020-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200529_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
