# Generated by Django 3.0.6 on 2020-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200530_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
