# Generated by Django 3.0.6 on 2020-05-30 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200530_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
