# Generated by Django 3.0.6 on 2020-05-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200530_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created_at']},
        ),
    ]
