# Generated by Django 3.0.6 on 2020-06-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_comment_img_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img_post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.Image'),
            preserve_default=False,
        ),
    ]
